In [1]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV

In [2]:
iris = pd.read_csv('Iris.csv')
iris.drop(['Id'], axis = 1, inplace = True)
iris.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
trainX, testX, trainY, testY = train_test_split(iris.drop(['Species'], axis =1), iris.Species, test_size= 0.25, 
                                                stratify = iris['Species'])

In [4]:
parameters_test = {
    'n_neighbors':list(range(1, 41))
}

In [5]:
classificator = KNeighborsClassifier(n_jobs= -1)
grid = GridSearchCV(classificator, parameters_test, scoring= 'accuracy', n_jobs=-1)

In [6]:
grid.fit(trainX, trainY)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
           weights='uniform'),
       fit_params=None, iid='warn', n_jobs=-1,
       param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='accuracy', verbose=0)

In [7]:
print(pd.DataFrame(grid.cv_results_))

    mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.002659  4.700217e-04         0.116751    1.693941e-03   
1        0.002659  4.700217e-04         0.116749    9.402681e-04   
2        0.002991  8.134201e-04         0.117747    4.705282e-04   
3        0.002992  0.000000e+00         0.116417    4.703588e-04   
4        0.001994  5.947204e-07         0.109862    8.136147e-04   
5        0.001662  4.701903e-04         0.111186    4.701341e-04   
6        0.001662  4.703589e-04         0.113181    4.701905e-04   
7        0.001662  4.696845e-04         0.113181    4.701341e-04   
8        0.008976  1.410458e-03         0.116609    7.313582e-04   
9        0.005321  1.247341e-03         0.109173    2.932207e-03   
10       0.002327  4.683925e-04         0.105520    4.688418e-04   
11       0.001663  4.766687e-04         0.106182    3.766376e-06   
12       0.002001  8.218040e-04         0.111527    2.347278e-03   
13       0.001330  4.617897e-04         0.110513

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split0_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split1_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split2_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\util

In [8]:
grid.best_params_

{'n_neighbors': 7}

In [9]:
classificator = KNeighborsClassifier(n_neighbors= 10, n_jobs= -1)
classificator.fit(trainX, trainY)
predict = classificator.predict(testX)

In [10]:
print(confusion_matrix(testY, predict))
print(classification_report(testY, predict))

[[12  0  0]
 [ 0 13  0]
 [ 0  0 13]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       1.00      1.00      1.00        13
 Iris-virginica       1.00      1.00      1.00        13

      micro avg       1.00      1.00      1.00        38
      macro avg       1.00      1.00      1.00        38
   weighted avg       1.00      1.00      1.00        38



In [11]:
trainX, testX, trainY, testY = train_test_split(iris.drop(['Species', 'SepalWidthCm', 'SepalLengthCm'], axis =1), iris.Species, test_size= 0.25, 
                                                stratify = iris['Species'])

In [12]:
classificator = KNeighborsClassifier(n_neighbors= 10, n_jobs= -1)
classificator.fit(trainX, trainY)
predict = classificator.predict(testX)
print(confusion_matrix(testY, predict))
print(classification_report(testY, predict))

[[13  0  0]
 [ 0 11  1]
 [ 0  1 12]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        13
Iris-versicolor       0.92      0.92      0.92        12
 Iris-virginica       0.92      0.92      0.92        13

      micro avg       0.95      0.95      0.95        38
      macro avg       0.95      0.95      0.95        38
   weighted avg       0.95      0.95      0.95        38



In [13]:
XC = iris.drop(['Species'], axis = 1) #X completo
XP = iris.drop(['SepalLengthCm', 'SepalWidthCm', 'Species'], axis=1) #X Parcial
Y = iris['Species']

In [14]:
from sklearn.model_selection import cross_val_score

In [15]:
KNN = KNeighborsClassifier(n_neighbors= 10, n_jobs= -1)
score = cross_val_score(KNN, XC, Y, cv=5)
print(score)

[0.96666667 1.         1.         0.93333333 1.        ]


In [16]:
print('A acuracia da Iris com todos atributos tem:')
print('Média: %0.2f e Desvio Padrão de +/-: %0.2f' % (np.mean(score), np.std(score)))

A acuracia da Iris com todos atributos tem:
Média: 0.98 e Desvio Padrão de +/-: 0.03


In [17]:
KNN = KNeighborsClassifier(n_neighbors= 10, n_jobs= -1)
score = cross_val_score(KNN, XP, Y, cv=5)
print(score)

[0.96666667 0.96666667 0.93333333 0.96666667 1.        ]


In [18]:
print('A acuracia da Iris só com atributo da Petalas tem:')
print('Média: %0.2f e Desvio Padrão de +/-: %0.2f' % (np.mean(score), np.std(score)))

A acuracia da Iris só com atributo da Petalas tem:
Média: 0.97 e Desvio Padrão de +/-: 0.02
