In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV

In [2]:
iris = pd.read_csv('Iris.csv')
iris.drop(['Id'], axis = 1, inplace = True)
iris.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
trainX, testX, trainY, testY = train_test_split(iris.drop(['Species'], axis =1), iris.Species, test_size= 0.25, 
                                                stratify = iris['Species'])

In [4]:
parameters_test = {
    'C':[0.1,1.0,10.0],
    'solver':['newton-cg', 'lbfgs']
}

In [5]:
classificator = LogisticRegression(n_jobs=-1)
grid = GridSearchCV(classificator, parameters_test, scoring= 'accuracy', n_jobs=-1)

In [6]:
grid.fit(trainX, trainY)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn', n_jobs=-1,
          penalty='l2', random_state=None, solver='warn', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid='warn', n_jobs=-1,
       param_grid={'C': [0.1, 1.0, 10.0], 'solver': ['newton-cg', 'lbfgs']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='accuracy', verbose=0)

In [7]:
print(pd.DataFrame(grid.cv_results_))

   mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.112265      0.000940         0.007315        0.000470     0.1   
1       0.110295      0.000479         0.006292        0.001261     0.1   
2       0.109962      0.000017         0.005960        0.000830       1   
3       0.109938      0.000000         0.006982        0.000000       1   
4       0.106179      0.001244         0.001005        0.000010      10   
5       0.105227      0.000487         0.000973        0.000046      10   

  param_solver                              params  split0_test_score  \
0    newton-cg   {'C': 0.1, 'solver': 'newton-cg'}           0.871795   
1        lbfgs       {'C': 0.1, 'solver': 'lbfgs'}           0.871795   
2    newton-cg   {'C': 1.0, 'solver': 'newton-cg'}           0.923077   
3        lbfgs       {'C': 1.0, 'solver': 'lbfgs'}           0.923077   
4    newton-cg  {'C': 10.0, 'solver': 'newton-cg'}           0.948718   
5        lbfgs      {'C': 10.0, 'sol

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split0_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split1_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split2_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\util

In [8]:
print(grid.best_params_)

{'C': 10.0, 'solver': 'newton-cg'}


In [9]:
classificator = LogisticRegression(C = 10.0, solver= 'newton-cg', n_jobs=-1)
classificator.fit(trainX, trainY)
predicts = classificator.predict(testX)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [10]:
print(confusion_matrix(testY, predicts))
print(classification_report(testY, predicts))

[[12  0  0]
 [ 0 12  1]
 [ 0  0 13]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       1.00      0.92      0.96        13
 Iris-virginica       0.93      1.00      0.96        13

      micro avg       0.97      0.97      0.97        38
      macro avg       0.98      0.97      0.97        38
   weighted avg       0.98      0.97      0.97        38



In [11]:
classificator.intercept_

array([  7.83017348,   6.6263406 , -18.21138184])

In [12]:
classificator.coef_

array([[-0.4492096 ,  1.54917733, -3.36846706, -1.33158145],
       [ 0.54725645, -3.41451369,  0.38524186, -1.63135346],
       [-1.82825593, -1.21660119,  4.96611045,  5.31291978]])

In [13]:
classificator.classes_

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [14]:
trainX, testX, trainY, testY = train_test_split(iris.drop(['Species', 'SepalWidthCm', 'SepalLengthCm'], axis =1), iris.Species, test_size= 0.25, 
                                                stratify = iris['Species'])

In [15]:
classificator = LogisticRegression(C = 10.0, solver= 'newton-cg', n_jobs=-1)
classificator.fit(trainX, trainY)
predict = classificator.predict(testX)
print(confusion_matrix(testY, predict))
print(classification_report(testY, predict))

[[13  0  0]
 [ 0 12  1]
 [ 0  1 11]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        13
Iris-versicolor       0.92      0.92      0.92        13
 Iris-virginica       0.92      0.92      0.92        12

      micro avg       0.95      0.95      0.95        38
      macro avg       0.95      0.95      0.95        38
   weighted avg       0.95      0.95      0.95        38



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [16]:
classificator.intercept_

array([ 11.46932575,  -2.64503158, -27.43646845])

In [17]:
classificator.coef_

array([[-3.93364985, -1.76482898],
       [ 1.38563656, -2.76115429],
       [ 3.6328406 ,  5.89424973]])

In [18]:
XC = iris.drop(['Species'], axis = 1) #X completo
XP = iris.drop(['SepalLengthCm', 'SepalWidthCm', 'Species'], axis=1) #X Parcial
Y = iris['Species']

In [19]:
from sklearn.model_selection import cross_val_score

In [20]:
SIG = LogisticRegression(C = 10.0, solver= 'newton-cg', n_jobs=-1)
score = cross_val_score(SIG, XC, Y, cv=5)
print(score)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-pa

[0.96666667 0.96666667 0.93333333 0.93333333 1.        ]


In [21]:
print('A acuracia da Iris com todos atributos tem:')
print('Média: %0.2f e Desvio Padrão de +/-: %0.2f' % (np.mean(score), np.std(score)))

A acuracia da Iris com todos atributos tem:
Média: 0.96 e Desvio Padrão de +/-: 0.02


In [22]:
SIG = LogisticRegression(C = 10.0, solver= 'newton-cg', n_jobs=-1)
score = cross_val_score(SIG, XP, Y, cv=5)
print(score)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


[0.96666667 0.96666667 0.93333333 0.9        1.        ]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [23]:
print('A acuracia da Iris só com atributo da Petalas tem:')
print('Média: %0.2f e Desvio Padrão de +/-: %0.2f' % (np.mean(score), np.std(score)))

A acuracia da Iris só com atributo da Petalas tem:
Média: 0.95 e Desvio Padrão de +/-: 0.03
