In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV

In [2]:
iris = pd.read_csv('Iris.csv')
iris.drop(['Id'], axis = 1, inplace = True)
iris.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
trainX, testX, trainY, testY = train_test_split(iris.drop(['Species'], axis =1), iris.Species, test_size= 0.25, 
                                                stratify = iris['Species'])

In [4]:
parameters_test = {
    'C':[0.1,1.0,10.0],
    'solver':['newton-cg', 'lbfgs']
}

In [5]:
classificator = LogisticRegression(n_jobs=-1)
grid = GridSearchCV(classificator, parameters_test, scoring= 'accuracy', n_jobs=-1)

In [6]:
grid.fit(trainX, trainY)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn', n_jobs=-1,
          penalty='l2', random_state=None, solver='warn', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid='warn', n_jobs=-1,
       param_grid={'C': [0.1, 1.0, 10.0], 'solver': ['newton-cg', 'lbfgs']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='accuracy', verbose=0)

In [7]:
print(pd.DataFrame(grid.cv_results_))

   mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.111170  4.710332e-04         0.005651    1.880311e-03     0.1   
1       0.109175  2.350445e-03         0.004986    2.821029e-03     0.1   
2       0.110504  4.705836e-04         0.006981    0.000000e+00       1   
3       0.109840  1.410515e-03         0.006981    0.000000e+00       1   
4       0.104905  4.743492e-04         0.004021    4.380389e-06      10   
5       0.104271  5.947204e-07         0.003965    1.946680e-07      10   

  param_solver                              params  split0_test_score  \
0    newton-cg   {'C': 0.1, 'solver': 'newton-cg'}           0.871795   
1        lbfgs       {'C': 0.1, 'solver': 'lbfgs'}           0.871795   
2    newton-cg   {'C': 1.0, 'solver': 'newton-cg'}           0.948718   
3        lbfgs       {'C': 1.0, 'solver': 'lbfgs'}           0.948718   
4    newton-cg  {'C': 10.0, 'solver': 'newton-cg'}           1.000000   
5        lbfgs      {'C': 10.0, 'sol

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split0_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split1_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split2_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\util

In [8]:
print(grid.best_params_)

{'C': 10.0, 'solver': 'newton-cg'}


In [10]:
classificator = LogisticRegression(C = 10.0, solver= 'newton-cg', n_jobs=-1)
classificator.fit(trainX, trainY)
predicts = classificator.predict(testX)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [11]:
print(confusion_matrix(testY, predicts))
print(classification_report(testY, predicts))

[[12  0  0]
 [ 0 11  2]
 [ 0  0 13]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       1.00      0.85      0.92        13
 Iris-virginica       0.87      1.00      0.93        13

      micro avg       0.95      0.95      0.95        38
      macro avg       0.96      0.95      0.95        38
   weighted avg       0.95      0.95      0.95        38



In [12]:
classificator.intercept_

array([  8.46295652,   6.77557111, -19.65604491])

In [13]:
classificator.coef_

array([[-0.56464816,  1.53245166, -3.37095338, -1.56028327],
       [ 0.19522853, -3.14362384,  0.92965704, -2.26982254],
       [-1.44110362, -2.13076038,  5.45120888,  4.96652539]])

In [14]:
classificator.classes_

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [17]:
trainX, testX, trainY, testY = train_test_split(iris.drop(['Species', 'SepalWidthCm', 'SepalLengthCm'], axis =1), iris.Species, test_size= 0.25, 
                                                stratify = iris['Species'])

In [18]:
classificator = LogisticRegression(C = 10.0, solver= 'newton-cg', n_jobs=-1)
classificator.fit(trainX, trainY)
predict = classificator.predict(testX)
print(confusion_matrix(testY, predict))
print(classification_report(testY, predict))

[[13  0  0]
 [ 0 12  1]
 [ 0  1 11]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        13
Iris-versicolor       0.92      0.92      0.92        13
 Iris-virginica       0.92      0.92      0.92        12

      micro avg       0.95      0.95      0.95        38
      macro avg       0.95      0.95      0.95        38
   weighted avg       0.95      0.95      0.95        38



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [19]:
classificator.intercept_

array([ 11.41899923,  -2.30853807, -33.98522951])

In [20]:
classificator.coef_

array([[-3.89409803, -1.7655335 ],
       [ 1.07042648, -2.10866133],
       [ 5.38507333,  4.55731086]])