In [1]:
import numpy as np
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV

In [2]:
iris = pd.read_csv('Iris.csv')
iris.drop(['Id'], axis = 1, inplace = True)
iris.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
trainX, testX, trainY, testY = train_test_split(iris.drop(['Species'], axis =1), iris.Species, test_size= 0.25, 
                                                stratify = iris['Species'])

In [4]:
momentun = lambda l : list(np.array(l) / 100.0)

In [5]:
momentun([10, 20])

[0.1, 0.2]

In [6]:
parameters_test = {
    'hidden_layer_sizes':[(10,), (10,5), (20,), (20, 10), (40, 20, 10)],
    'activation':['identity', 'logistic', 'tanh', 'relu'],
    'solver':['lbfgs', 'sgd', 'adam'],
    'momentum': momentun(list(range(10, 100, 10)))
}

In [7]:
classificator = MLPClassifier(tol=0.0000001, max_iter= 1400)
grid = GridSearchCV(classificator, parameters_test, scoring= 'accuracy', n_jobs=-1)

In [8]:
grid.fit(trainX, trainY)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1400) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1400, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=1e-07,
       validation_fraction=0.1, verbose=False, warm_start=False),
       fit_params=None, iid='warn', n_jobs=-1,
       param_grid={'hidden_layer_sizes': [(10,), (10, 5), (20,), (20, 10), (40, 20, 10)], 'activation': ['identity', 'logistic', 'tanh', 'relu'], 'solver': ['lbfgs', 'sgd', 'adam'], 'momentum': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='accuracy', verbose=0)

In [9]:
print(pd.DataFrame(grid.cv_results_))

     mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0         0.185161      0.078050         0.001330    4.701903e-04   
1         0.506961      0.004083         0.001835    6.283727e-04   
2         0.525304      0.004785         0.001663    4.697407e-04   
3         0.164004      0.072446         0.001507    4.176724e-04   
4         0.509406      0.004192         0.001330    4.700217e-04   
5         0.545387      0.020115         0.001662    4.699657e-04   
6         0.154262      0.046049         0.000998    1.946680e-07   
7         0.517879      0.006217         0.001662    4.701342e-04   
8         0.545655      0.002503         0.001662    4.700779e-04   
9         0.159574      0.065837         0.001995    1.123916e-07   
10        0.518402      0.009462         0.001330    4.700779e-04   
11        0.553879      0.008842         0.001015    2.461684e-05   
12        0.189825      0.120756         0.000998    2.973602e-07   
13        0.500835      0.006781  

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split0_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split1_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split2_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\util

In [10]:
grid.best_params_

{'activation': 'identity',
 'hidden_layer_sizes': (10,),
 'momentum': 0.2,
 'solver': 'adam'}

In [11]:
classificator = MLPClassifier(tol=0.0000001, max_iter= 1400, activation='identity', hidden_layer_sizes=(10, 5), momentum = 0.7)
classificator.fit(trainX, trainY)
predict = classificator.predict(testX)
print(confusion_matrix(testY, predict))
print(classification_report(testY, predict))

[[13  0  0]
 [ 0 13  0]
 [ 0  1 11]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        13
Iris-versicolor       0.93      1.00      0.96        13
 Iris-virginica       1.00      0.92      0.96        12

      micro avg       0.97      0.97      0.97        38
      macro avg       0.98      0.97      0.97        38
   weighted avg       0.98      0.97      0.97        38



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1400) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [12]:
trainX, testX, trainY, testY = train_test_split(iris.drop(['Species', 'SepalWidthCm', 'SepalLengthCm'], axis =1), iris.Species, test_size= 0.25, 
                                                stratify = iris['Species'])

In [13]:
classificator = MLPClassifier(tol=0.0000001, max_iter= 1400, activation='identity', hidden_layer_sizes=(10, 5), momentum = 0.7)
classificator.fit(trainX, trainY)
predict = classificator.predict(testX)
print(confusion_matrix(testY, predict))
print(classification_report(testY, predict))

[[13  0  0]
 [ 0 13  0]
 [ 0  0 12]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        13
Iris-versicolor       1.00      1.00      1.00        13
 Iris-virginica       1.00      1.00      1.00        12

      micro avg       1.00      1.00      1.00        38
      macro avg       1.00      1.00      1.00        38
   weighted avg       1.00      1.00      1.00        38



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1400) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [14]:
classificator.coefs_

[array([[ 0.28681187, -0.6261724 , -0.02451678,  0.0571237 , -0.23744967,
         -0.62494348, -0.7529671 , -0.02278198,  0.49960451, -0.54101324],
        [ 0.60657583, -1.004899  , -0.58462274, -0.20201561, -0.71494793,
         -0.3734379 , -0.07887031,  0.92958493, -0.86056569,  0.39941591]]),
 array([[-9.78167398e-01, -3.97408925e-01,  3.17428624e-01,
         -3.83901943e-01,  1.45594752e-01],
        [ 7.39409721e-01, -1.84441779e-01,  4.72179291e-01,
          1.04494132e-03, -1.05846109e+00],
        [ 8.62199775e-01,  1.80708672e-01, -3.37342148e-01,
         -1.65348820e-01, -5.73048757e-01],
        [ 3.13601436e-01,  3.40573190e-01,  7.49212905e-01,
          5.95449998e-01, -3.08329023e-01],
        [ 6.86432274e-01, -2.81211809e-01,  4.17896419e-01,
          5.43343294e-01,  1.49235309e-01],
        [-7.14130719e-01,  2.31383622e-01, -3.32480242e-01,
          4.52027407e-01,  3.69584903e-01],
        [ 4.26454759e-01, -4.17193483e-01,  6.09711090e-01,
          3.5934

In [15]:
XC = iris.drop(['Species'], axis = 1) #X completo
XP = iris.drop(['SepalLengthCm', 'SepalWidthCm', 'Species'], axis=1) #X Parcial
Y = iris['Species']

In [16]:
from sklearn.model_selection import cross_val_score

In [23]:
NeuralNetwork = MLPClassifier(tol=0.0000001, max_iter= 21400, activation='identity', hidden_layer_sizes=(10, 5), momentum = 0.7)
score = cross_val_score(NeuralNetwork, XC, Y, cv=5)
print(score)

[1.         1.         0.93333333 0.93333333 1.        ]


In [24]:
print('A acuracia da Iris com todos atributos tem:')
print('Média: %0.2f e Desvio Padrão de +/-: %0.2f' % (np.mean(score), np.std(score)))

A acuracia da Iris com todos atributos tem:
Média: 0.97 e Desvio Padrão de +/-: 0.03


In [25]:
NeuralNetwork = MLPClassifier(tol=0.0000001, max_iter= 21400, activation='identity', hidden_layer_sizes=(10, 5), momentum = 0.7)
score = cross_val_score(NeuralNetwork, XP, Y, cv=5)
print(score)

[0.96666667 0.96666667 0.93333333 0.9        1.        ]


In [26]:
print('A acuracia da Iris só com atributo da Petalas tem:')
print('Média: %0.2f e Desvio Padrão de +/-: %0.2f' % (np.mean(score), np.std(score)))

A acuracia da Iris só com atributo da Petalas tem:
Média: 0.95 e Desvio Padrão de +/-: 0.03
