In [1]:
import numpy as np
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV

In [2]:
iris = pd.read_csv('Iris.csv')
iris.drop(['Id'], axis = 1, inplace = True)
iris.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
trainX, testX, trainY, testY = train_test_split(iris.drop(['Species'], axis =1), iris.Species, test_size= 0.25, 
                                                stratify = iris['Species'])

In [4]:
momentun = lambda l : list(np.array(l) / 100.0)

In [5]:
momentun([10, 20])

[0.1, 0.2]

In [6]:
parameters_test = {
    'hidden_layer_sizes':[(10,), (10,5), (20,), (20, 10), (40, 20, 10)],
    'activation':['identity', 'logistic', 'tanh', 'relu'],
    'solver':['lbfgs', 'sgd', 'adam'],
    'momentum': momentun(list(range(10, 100, 10)))
}

In [7]:
classificator = MLPClassifier(tol=0.0000001, max_iter= 1400)
grid = GridSearchCV(classificator, parameters_test, scoring= 'accuracy', n_jobs=-1)

In [8]:
grid.fit(trainX, trainY)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1400) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1400, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=1e-07,
       validation_fraction=0.1, verbose=False, warm_start=False),
       fit_params=None, iid='warn', n_jobs=-1,
       param_grid={'hidden_layer_sizes': [(10,), (10, 5), (20,), (20, 10), (40, 20, 10)], 'activation': ['identity', 'logistic', 'tanh', 'relu'], 'solver': ['lbfgs', 'sgd', 'adam'], 'momentum': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='accuracy', verbose=0)

In [9]:
print(pd.DataFrame(grid.cv_results_))

     mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0         0.064827      0.028986         0.001662    4.697969e-04   
1         0.512649      0.008579         0.001662    4.696845e-04   
2         0.549219      0.001695         0.001995    7.018853e-07   
3         0.035572      0.022469         0.001662    4.704712e-04   
4         0.526280      0.005777         0.001995    8.139067e-04   
5         0.563180      0.008475         0.001662    4.700217e-04   
6         0.065823      0.023305         0.001994    1.946680e-07   
7         0.517616      0.004309         0.001662    4.703588e-04   
8         0.562828      0.016775         0.001330    4.705837e-04   
9         0.067153      0.031426         0.000998    4.052337e-07   
10        0.520276      0.012224         0.003324    3.290995e-03   
11        0.537915      0.007697         0.000997    2.973602e-07   
12        0.034574      0.022979         0.001330    4.697407e-04   
13        0.509167      0.002821  

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split0_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split1_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split2_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\util

In [10]:
grid.best_params_

{'activation': 'identity',
 'hidden_layer_sizes': (10, 5),
 'momentum': 0.7,
 'solver': 'adam'}

In [12]:
classificator = MLPClassifier(tol=0.0000001, max_iter= 1400, activation='identity', hidden_layer_sizes=(10, 5), momentum = 0.7)
classificator.fit(trainX, trainY)
predict = classificator.predict(testX)
print(confusion_matrix(testY, predict))
print(classification_report(testY, predict))

[[13  0  0]
 [ 0 11  1]
 [ 0  0 13]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        13
Iris-versicolor       1.00      0.92      0.96        12
 Iris-virginica       0.93      1.00      0.96        13

      micro avg       0.97      0.97      0.97        38
      macro avg       0.98      0.97      0.97        38
   weighted avg       0.98      0.97      0.97        38



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1400) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [13]:
trainX, testX, trainY, testY = train_test_split(iris.drop(['Species', 'SepalWidthCm', 'SepalLengthCm'], axis =1), iris.Species, test_size= 0.25, 
                                                stratify = iris['Species'])

In [14]:
classificator = MLPClassifier(tol=0.0000001, max_iter= 1400, activation='identity', hidden_layer_sizes=(10, 5), momentum = 0.7)
classificator.fit(trainX, trainY)
predict = classificator.predict(testX)
print(confusion_matrix(testY, predict))
print(classification_report(testY, predict))

[[12  0  0]
 [ 0 12  1]
 [ 0  0 13]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       1.00      0.92      0.96        13
 Iris-virginica       0.93      1.00      0.96        13

      micro avg       0.97      0.97      0.97        38
      macro avg       0.98      0.97      0.97        38
   weighted avg       0.98      0.97      0.97        38



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1400) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [16]:
classificator.coefs_

[array([[ 0.34045312, -0.67436026, -0.68022079,  0.67872878, -0.16393741,
         -0.64526665,  0.51581791, -0.02150414, -0.05518743, -0.67269794],
        [-0.28040489, -0.470568  ,  0.03959476, -0.06537006,  0.11414749,
          0.54178114,  0.49981833, -1.07580538,  0.11384105, -0.54900175]]),
 array([[ 0.41025945, -0.34880281,  0.40089914,  0.35132721, -0.4703382 ],
        [-0.12262787,  0.04355199,  0.42244533, -0.47972606,  0.10202895],
        [ 0.69315793,  0.57004735,  0.20733787, -0.49442033,  0.18556945],
        [ 0.01959815,  0.22898907,  0.33150027,  0.74411859,  0.20875503],
        [-0.59037982, -0.15701408, -0.29638293,  0.63819829,  0.06699763],
        [-0.1842747 , -0.57111963,  0.13577806,  0.53365539,  0.44367411],
        [ 0.42785727,  0.38717987, -0.36365111, -0.17843346, -0.03079344],
        [ 0.59292874,  0.37979628, -0.1943452 , -0.66483891, -0.76052049],
        [ 0.50052925,  0.28654333,  0.84681926, -0.98133463, -0.54455789],
        [ 0.12504051, -0.